// /src/interfaces/project.ts

interface Project {
    projectId: string;
    projectName: string;
    projectDescription: string;
    projectElements: string;
    approvedBudget: number;
    originalContractValueDesign: number;
    originalContractValueSupervision: number,
    originalContractValueContractor: number;
    costSqM: any;
    costPlots: any;
    allocatedCurYearBudget: number;
    plannedOneBudget: number;
    plannedTwoBudget: number;
    plannedThreeBudget: number;
    plannedFourBudget: number;
    plannedFiveBudget: number;
    plannedBudgetLaterFive: number;
    variationOrderNo: number;
    variationOrderTotal: number;
    variationOrderAllocateBudgetTotal: number;
    resolutionDate: any;
    resolutionRecvdDate: any;
    forecastQ1CurYear: number;
    expendituresQ1CurYear: number;
    achievedMilestones: any;
    forecastQ2CurYear: number;
    expendituresQ2CurYear: number;
    forecastQ3CurYear: number;
    expendituresQ3CurYear: number;
    forecastQ4CurYear: number;
    expendituresQ4CurYear: number;
    forecastExpendituresCurYear: number;
    cumulativeExpenditures: number;
    designAwardDate: string;
    supervisionAwardDate: any;
    contractorAwardDate: any;
    originalPlannedComDate: string;
    actualForecastComDate: string;
    originalProgress: number;
    revisedProgress: number;
    actualProgress: number;
    challenges: string;
    measures: string;
    location: string;
    designName: string;
    designLicNo: string;
    supervisionName: string;
    supervisionLicenseNo: string;
    contractorName: string;
    contractorLicNo: string;
    pmName: string;
    pmPhoneNo: string;
    pmEmail: string;
    startYear: any;
    currentYear: any;
    etlDate: string;
    entryDate: string;
    dofNo: any;
    note: string;
    category: string;
    categoryId: number;
    phase: string;
    phaseId: number;
    status: string;
    statusId: number;
    entity: string;
    pmNationality: string;
    resolution: any;
    comments: any;
    files: any;
}


export default Project;